version: '3.8'
services:
  go-server:
    build:
        context: ./go_app
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    volumes:
      - .:/app
      - go_cache:/root/.cache/go-build
      - go_mod:/go/pkg/mod
    depends_on:
      - db
    restart: unless-stopped
  nginx:
    build:
        context: .
        dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - go-server
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
