"""Add stastashes

Revision ID: 5c9b1a72ba07
Revises: 9dc072a5ccee
Create Date: 2024-03-12 19:25:51.038525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9b1a72ba07'
down_revision: Union[str, None] = '9dc072a5ccee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('x_dir', sa.Float(), nullable=False),
    sa.Column('y_dir', sa.Float(), nullable=False),
    sa.Column('z_dir', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_position_id'), 'position', ['id'], unique=False, schema='game')
    op.create_table('stash',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('avg_items_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['game.position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_stash_id'), 'stash', ['id'], unique=False, schema='game')
    op.create_index(op.f('ix_game_stash_position_id'), 'stash', ['position_id'], unique=False, schema='game')
    op.create_table('stash_items',
    sa.Column('stash_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['game.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stash_id'], ['game.stash.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stash_id', 'item_id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_stash_items_item_id'), 'stash_items', ['item_id'], unique=False, schema='game')
    op.create_index(op.f('ix_game_stash_items_stash_id'), 'stash_items', ['stash_id'], unique=False, schema='game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_stash_items_stash_id'), table_name='stash_items', schema='game')
    op.drop_index(op.f('ix_game_stash_items_item_id'), table_name='stash_items', schema='game')
    op.drop_table('stash_items', schema='game')
    op.drop_index(op.f('ix_game_stash_position_id'), table_name='stash', schema='game')
    op.drop_index(op.f('ix_game_stash_id'), table_name='stash', schema='game')
    op.drop_table('stash', schema='game')
    op.drop_index(op.f('ix_game_position_id'), table_name='position', schema='game')
    op.drop_table('position', schema='game')
    # ### end Alembic commands ###
