"""Fix

Revision ID: a68bb495de52
Revises: 
Create Date: 2024-02-20 09:07:22.808012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68bb495de52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_table('bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.Column('max_money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_bank_id'), 'bank', ['id'], unique=False, schema='game')
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='game'
    )
    op.create_index(op.f('ix_game_category_id'), 'category', ['id'], unique=False, schema='game')
    op.create_table('factions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_factions_id'), 'factions', ['id'], unique=False, schema='game')
    op.create_table('trader',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='game'
    )
    op.create_index(op.f('ix_game_trader_id'), 'trader', ['id'], unique=False, schema='game')
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['game.category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name'),
    schema='game'
    )
    op.create_index(op.f('ix_game_items_id'), 'items', ['id'], unique=False, schema='game')
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['game.factions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_players_id'), 'players', ['id'], unique=False, schema='game')
    op.create_table('bank_deposit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['game.bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['game.players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_bank_deposit_id'), 'bank_deposit', ['id'], unique=False, schema='game')
    op.create_table('trader_items',
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['game.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trader_id'], ['game.trader.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trader_id', 'item_id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_trader_items_item_id'), 'trader_items', ['item_id'], unique=False, schema='game')
    op.create_index(op.f('ix_game_trader_items_trader_id'), 'trader_items', ['trader_id'], unique=False, schema='game')
    op.create_table('trader_items_points',
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('required_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id', 'item_id'], ['game.trader_items.trader_id', 'game.trader_items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trader_id', 'item_id'),
    schema='game'
    )
    op.create_index(op.f('ix_game_trader_items_points_item_id'), 'trader_items_points', ['item_id'], unique=False, schema='game')
    op.create_index(op.f('ix_game_trader_items_points_trader_id'), 'trader_items_points', ['trader_id'], unique=False, schema='game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_trader_items_points_trader_id'), table_name='trader_items_points', schema='game')
    op.drop_index(op.f('ix_game_trader_items_points_item_id'), table_name='trader_items_points', schema='game')
    op.drop_table('trader_items_points', schema='game')
    op.drop_index(op.f('ix_game_trader_items_trader_id'), table_name='trader_items', schema='game')
    op.drop_index(op.f('ix_game_trader_items_item_id'), table_name='trader_items', schema='game')
    op.drop_table('trader_items', schema='game')
    op.drop_index(op.f('ix_game_bank_deposit_id'), table_name='bank_deposit', schema='game')
    op.drop_table('bank_deposit', schema='game')
    op.drop_index(op.f('ix_game_players_id'), table_name='players', schema='game')
    op.drop_table('players', schema='game')
    op.drop_index(op.f('ix_game_items_id'), table_name='items', schema='game')
    op.drop_table('items', schema='game')
    op.drop_index(op.f('ix_game_trader_id'), table_name='trader', schema='game')
    op.drop_table('trader', schema='game')
    op.drop_index(op.f('ix_game_factions_id'), table_name='factions', schema='game')
    op.drop_table('factions', schema='game')
    op.drop_index(op.f('ix_game_category_id'), table_name='category', schema='game')
    op.drop_table('category', schema='game')
    op.drop_index(op.f('ix_game_bank_id'), table_name='bank', schema='game')
    op.drop_table('bank', schema='game')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
